### ISSUE TITLE
running issue

### ISSUE THREAD

**Issue by Spaceish** [supertiger1234/nertivia-desktop-app#11]
![Capture](https://user-images.githubusercontent.com/63191158/101659322-99600900-3a4e-11eb-9306-8a1780b579d5.PNG)

**Comment by Toby222** [comment]
When does this occur?
Does it happen consistently?

**Comment by Spaceish** [comment]
yes

**Comment by Spaceish** [comment]
it happens whenever i run "electron ." or "electron main"

**Comment by SupertigerDev** [comment]
Did u do `npm i`?

**Comment by Spaceish** [comment]
still doesn't work

**Comment by Spaceish** [comment]
I think I need to make things clear, there's nothing wrong with the build, but the error occurs when i try to run it from source

**Comment by Spaceish** [comment]
nvm i just installed a older version
