### ISSUE TITLE
"Email is blacklisted" error when creating account

### ISSUE THREAD

**Issue by DizzyDaisy909** [supertiger1234/nertivia-desktop-app#21]
I made an account using my email, and it said it was blacklisted. I've never used this site before, so it's not from being banned before. The email is from Proton Mail, if that matters. Can you please fix this? I'm trying to move away from Gmail.

**Comment by chris9740** [comment]
I'm not one of the devs but, it looks like protonmail.com has been blacklisted completely. Not sure why, I think they should remove it from the blacklist

**Comment by DizzyDaisy909** [comment]
> I'm not one of the devs but, it looks like protonmail.com has been blacklisted completely. Not sure why, I think they should remove it from the blacklist

Yes, they should, it's a great email service

**Comment by SupertigerDev** [comment]
How easy is it to create a protonmail email account? If its too easy, people can abuse and create spam accounts.

**Comment by chris9740** [comment]
From ProtonMail, "Generally speaking, attempting to create multiple accounts will trigger more difficult verification methods such as Email or SMS, although there are also other factors that we consider."

In my opinion, I don't think it will generate that much spam. If people wanted to circumvent the blacklist, they would have used an alternative service, as there are many out there. I think it makes sense to block the addresses that have a high frequency of spam, but not one that have very common legitimate use, such as ProtonMail.

**Comment by SupertigerDev** [comment]
Oh, alright. I'll remove the blacklist when I get on my pc 😃 thanks

**Comment by SupertigerDev** [comment]
https://github.com/supertiger1234/Nertivia-Server/commit/1d604dd20366606ff1084a47837115d84a96ff9a

Done, thanks!
